### ISSUE TITLE
Add overlay image

### ISSUE THREAD

**Issue by chriship** [cloudinary-devs/cloudinary-laravel#36]
Hi,

Is it possible to add a watermark/overaly image to another image or video using this package?

**Comment by papa28x4** [comment]
Try this:

$imageUrl = cloudinary()->upload($file->getRealPath(), [
                                        'folder' => 'images',
                                        'transformation' =>[
                                            ["width" => 1000, "height" => 1000, "crop" => "limit"],
                                            ["overlay" => "public-id", "flags" => "relative", "width" => 0.5]
                                        ] ,
                                        
                            ])->getSecurePath();

Replace public-id with the actual public id of the watermark image

**Comment by chriship** [comment]
Thanks, is it possible to use a url for the watemark image?

**Comment by papa28x4** [comment]
I don't know if it's possible. I have tried using it and it didn't work.

**Comment by unicodeveloper** [comment]
@chriship do you mean a URL that's not on Cloudinary?

**Comment by unicodeveloper** [comment]
@chriship this should help/work https://cloudinary.com/documentation/layers#remote_image_overlays
