### ISSUE TITLE
How to transform image/video before calling attachMedia()

### ISSUE THREAD

**Issue by nattive** [cloudinary-devs/cloudinary-laravel#5]
Its not included in the documentary, How can i resize, transform media with the attachMedia() function? I checked the function and i saw it only receive one parameter

**Comment by unicodeveloper** [comment]
@nattive the attachMedia() function was built just for attaching files to your models. You can't resize, or transform media directly with it.

However, this is a good idea I can work on over the weekend @nattive.

**Comment by nattive** [comment]
awesome!!! i will be expecting

**Comment by Adtrex** [comment]
I would also like to try this out. Can I be assigned to this?

**Comment by Adtrex** [comment]
I would also like to try this out. Can I be assigned to this?

**Comment by unicodeveloper** [comment]
Sure. Assigning this to you now @Adtrex

**Comment by unicodeveloper** [comment]
Assigned 🌟
