### ISSUE TITLE
detachMedia deletes ALL images attached to an entity

### ISSUE THREAD

**Issue by ttrolololll** [cloudinary-devs/cloudinary-laravel#51]
https://github.com/cloudinary-labs/cloudinary-laravel/blob/ab0dc2d2dfefbeb67c7b282b72e6203802c36582/src/MediaAlly.php#L82

This method is problematic. It gets ALL the images associated to the entity, and deletes them all...

Need to have an if statement to check for nullness of `$media` param, if not null, only delete given media, else then delete all.

For a destructive action like delete all media, it should even be consider to have a separate method just for that...

**Comment by SlimGee** [comment]
I wrote the method, for some reason it works just as expected, checks the nullness and only delete the passed media, you can write a unit test

**Comment by Delaney** [comment]
Hey @unicodeveloper I'd like to work on this

**Comment by Delaney** [comment]
@ttrolololll the method seems to work as intended.

@unicodeveloper the method could possibly be extended to also accept a collection and delete multiple media at once
