### ISSUE TITLE
Get video url by public_id returning an empty string

### ISSUE THREAD

**Issue by ayech0x2** [cloudinary-devs/cloudinary-laravel#82]
I'm trying to get a video url using this method: 

`$url = Cloudinary::getUrl("public_id_goes_here");`

When printing the url variable, it always returns `""` ( an empty string ) 

The asset method in `Cloudinary\Api\Admin` trait is always taking `$assetType` as an **image**

When i hardcode it and use **video** instead of **image** it works as expected. 

How can I get the URL of a video, when the getUrl method doesn't accept any other parameters!

Is this a bug or am I missing something here?

Thank you in advance.

**Comment by Mdhesari** [comment]
Hello @ayech0x2 

I think this is a bug and I've fixed it manually in my codebase

**Comment by unicodeveloper** [comment]
@ayech0x2 For video links, you need to use `$url = Cloudinary::getVideo("public_id_goes_here");`

**Comment by unicodeveloper** [comment]
@Mdhesari just simply use `$url = Cloudinary::getVideo("public_id_goes_here"); ` for videos. No need to fix anything.

**Comment by AndikanGabriel** [comment]
@unicodeveloper how about checking for the existence of a file?

Using `Storage::fileExists($publicId)` will fail if the file is a video, but changing the asset type to `video` passes as @Mdhesari noted.

This, appears to be a bug.

**Comment by joshmanders** [comment]
@AndikanGabriel can you open a new issue about this so I can take care of it?

**Comment by AndikanGabriel** [comment]
@joshmanders, yes, I can. I will do that shortly.
