### ISSUE TITLE
NotSupportingVisibilityTrait not found

### ISSUE THREAD

**Issue by Mdhesari** [cloudinary-devs/cloudinary-laravel#83]
Hey there

I've been using cloudinary-laravel for a while and after updating to laravel 9.x I get this error.

It seems that league/flysystem team have removed this trait and interface.

**Comment by unicodeveloper** [comment]
@Mdhesari Please make sure you update the package version to at least 2.0.0. Only the v2 works with Laravel 9.

**Comment by Mdhesari** [comment]
@unicodeveloper I've tried that and still no hope

**Comment by unicodeveloper** [comment]
I just tried it now locally and it works. Can I know see your composer.json? or is there a way you can reproduce it in a repo and send the link? @Mdhesari

**Comment by Mdhesari** [comment]
"league/flysystem": "^2.0.0"

this is the way I require it but it install 2.5

is it correct? 

@unicodeveloper

**Comment by unicodeveloper** [comment]
Just to be sure. Is there a reason why you are manually requiring this package `league/flysystem ` ?

**Comment by Mdhesari** [comment]
I was trying to use the cloudinary package for laravel 9 but it seems that laravel is locked to league/flysystem 3.*

**Comment by Mdhesari** [comment]
So I think we need to update CloudinaryAdapter class in order to fix the problem

**Comment by unicodeveloper** [comment]
Yes laravel 9 is locked to league/flysystem 3.* @Mdhesari

**Comment by Mdhesari** [comment]
Do you have any idea what we changes we could make in order to make it work with the new version of league/flsystem

**Comment by unicodeveloper** [comment]
In the latest version of CloudinaryAdapter, I also follow the v3 rules of league/flysystem. In fact, I released a version 2 of this package just to work with Laravel 9 and Flystem 3. So we don't need to update anything

**Comment by unicodeveloper** [comment]
@Mdhesari What I need to understand is: Why are you trying to use a lower version of league/flystem?

**Comment by Mdhesari** [comment]
@unicodeveloper 

Man I'm a fool :))

I thought you don't have new version for laravel 9 so I was trying to make the older version work with laravel 9

**Comment by unicodeveloper** [comment]
Hahahaha, you're not a fool. I guess you just misunderstood it. I'm glad you have figured it out now @Mdhesari 💯

**Comment by unicodeveloper** [comment]
You are welcome @Mdhesari ❤️

**Comment by Mdhesari** [comment]
@unicodeveloper 

do you have any changelog for new version?

**Comment by unicodeveloper** [comment]
It's in the [releases log here](https://github.com/cloudinary-devs/cloudinary-laravel/releases)

**Comment by unicodeveloper** [comment]
@Mdhesari do you have this `CLOUDINARY_URL=xxxxxxxxx` in your .env file?

**Comment by Mdhesari** [comment]
@unicodeveloper yess I have them all

**Comment by Mdhesari** [comment]
@unicodeveloper I hadn't this issue before and my env variables are available.

I've cleared cache and still get this error.

even checked it in my tinker and it gets the cloudinary_url correctly

**Comment by unicodeveloper** [comment]
Maybe you need to do a composer dump-autoload

**Comment by Mdhesari** [comment]
@unicodeveloper I've almost done everything :))

when something doesn't want to work just it doesn't 😆

**Comment by Mdhesari** [comment]
did you change any configuration stuff?
@unicodeveloper

**Comment by unicodeveloper** [comment]
I did not. @Mdhesari

**Comment by unicodeveloper** [comment]
This is a laravel repo I just created. 

- Uses Laravel 9
- Uses the latest version of Cloudinary Laravel

Clone, do a composer install, ensure the .env file has the right cloudinary values and run `php artisan serve `

You can use it as an example to inspect yours and figure out what's wrong @Mdhesari

**Comment by Mdhesari** [comment]
@unicodeveloper 

I've find out the problem that was about cloudinary name

fixed it by adding this to my app service provider register() 

        Configuration::instance(['cloud' => ['cloud_name' => env('CLOUDINARY_NAME'))]]);

**Comment by unicodeveloper** [comment]
Interesting. If you have `config/cloudinary.php` and your CLOUDINARY_URL in your env has the right value, then I am not sure you would have needed to do that though.

**Comment by Mdhesari** [comment]
@unicodeveloper 

yeah it was working before but now I was amazed too!

**Comment by brenjt** [comment]
Any plans on updating this bug? It still exists on 2.1.0 and no new versions have been released.

**Comment by unicodeveloper** [comment]
@brenjt please did you try it with the example repo I added in this thread? 

I can't seem to reproduce the error on my end

**Comment by jayjfletcher** [comment]
@unicodeveloper I can confirm there is a break when upgrading from 2.0 to 2.1, It looks like there was some regression.

Please look at src/CloudinaryAdapter.php from 1.0 -> 2.0-> 2.1 specifically the use of NotSupportingVisibilityTrait which doesn't exist anymore

There was definitely code regression.
