### ISSUE TITLE
Add custom analytics code for generated Cloudinary URLs

### ISSUE THREAD

**Issue by colbyfayock** [cloudinary-devs/cloudinary-laravel#84]
To give the ability to track Laravel usage separate from the standard PHP usage, we'd like to add a custom Analytics ID

The Analytics token is appended at the end of Cloudinary URLs as a query parameter by the SDKs, giving us the ability to have insights as to what SDKs or tools are making Cloudinary requests.

Here's the relevant code as an example in a test from the PHP library:

https://github.com/cloudinary/cloudinary_php/blob/27187ef3992b149878ef26a69934fc72bda2fa48/tests/Unit/Asset/AnalyticsTest.php#L61

To implement, replace `MockAnalytics` with `Analytics` and set the real versions:
* `sdkCode`: `W`
* `sdkVersion`: the current version of this Laravel plugin (ideally dynamically added)
* `techVersion`: the current Laravel version being used (ideally dynamically added)

**Comment by unicodeveloper** [comment]
Fixed in [2.0.2](https://github.com/cloudinary-devs/cloudinary-laravel/releases/tag/2.0.2)
