### ISSUE TITLE
Publish Laravel 10 support to Packagist

### ISSUE THREAD

**Issue by scajal** [cloudinary-devs/cloudinary-laravel#88]

**Comment by Alexander-Hagemeier** [comment]
Would really appreciate support for Laravel 10 as I use this package and currently I can't update to Laravel 10.

**Comment by unicodeveloper** [comment]
@hagealex the latest version already supports Laravel 10. https://github.com/cloudinary-devs/cloudinary-laravel/releases/tag/2.0.3
