### ISSUE TITLE
How to get upload image link from widget "x-cld-upload-button"

### ISSUE THREAD

**Issue by mahmoudelgharabawi** [cloudinary-devs/cloudinary-laravel#95]
i try to use ""x-cld-upload-button" But i can't understand How i can get the link after i uploaded image i want the link so as i can store in my model >>> using "php laravel"  i need more details or example to know how to use this ....

**Comment by unicodeveloper** [comment]
@sccalabr Are you still interested in this? 

The `x-cld-upload-button` calls the JavaScript widget that opens up the modal and then the file is uploaded to Cloudinary.

This is the code https://github.com/cloudinary-devs/cloudinary-laravel/blob/master/resources/views/components/button.blade.php

**Comment by unicodeveloper** [comment]
So we need a way to pass the link back to PHP and make it accessible for it to be stored anywhere.

**Comment by Delaney** [comment]
Hey @unicodeveloper added this functionality. My implementation works fine, but I'm wondering if there's a cleaner way to go about it.
